apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "powersync-helm-chart-demo.fullname" . }}-sync-rules
  namespace: {{ .Values.namespace }}
data:
  sync_rules.yaml: |-
    {{ .Values.syncRules.data | nindent 4 }}
immutable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "powersync-helm-chart-demo.fullname" . }}-base-env
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
immutable: true