apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powersync-helm-chart-demo.fullname" . }}-config
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Config is JSON that gets converted to base64
  config.json: {{ toJson .Values.powersyncConfig | b64enc }}
immutable: true